### ISSUE TITLE
Doctest crashes with ghc-8.10.1 and typechecker plugins

### ISSUE THREAD

**Issue by leonschoorl** [sol/doctest#264]
When testing files that use a typechecker plugin with ghc-8.10, it crashes during initialization of that plugin.

I created a simplified version of my setup here: https://github.com/leonschoorl/test-doctest

It works fine with 8.8.3, but with 8.10.1:
```
$ git clone https://github.com/leonschoorl/test-doctest.git
$ cd test-doctest
$ cabal run --write-ghc-environment=always -w ghc-8.10.1 test-doctests
MyLib.hs:1:1: error:
    Bad interface file: [..]/test-doctests/dist-newstyle/build/x86_64-linux/ghc-8.10.1/dummy-plugin-0.1.0.0/build/DummyDefs.hi
        Something is amiss; requested module  dummy-plugin-0.1.0.0:DummyDefs differs
        from name found in the interface file ghci-8.10.1:DummyDefs (if these names look the same, try again with -dppr-debug)
  |
1 | {-# OPTIONS_GHC -fplugin DummyPlugin   #-}
```

Confusingly if I add this `-dppr-debug` the two printed names become the same (and seemingly correct):
```
MyLib.hs:1:1: error:
    Bad interface file: [..]/test-doctests/dist-newstyle/build/x86_64-linux/ghc-8.10.1/dummy-plugin-0.1.0.0/build/DummyDefs.hi
        Something is amiss; requested module  dummy-plugin-0.1.0.0-inplace:DummyDefs differs
        from name found in the interface file dummy-plugin-0.1.0.0-inplace:DummyDefs (if these names look the same, try again with -dppr-debug)
  |
1 | {-# OPTIONS_GHC -fplugin DummyPlugin  -dppr-debug #-}
  | ^
```

I traced it down to the typechecking done inside of `Extract.parse`.
While the full cause might be something with the way the GHC session is setup at this point.
Is there any reason to do more that just parsing here?

The problem disappears when I simply remove this typechecking:
https://github.com/leonschoorl/doctest/commit/8aeee0a89b077d7dcb401fa1b380d9a51f94e634
And the testsuite still passes.

**Comment by quasicomputational** [comment]
Thanks for the report! The reproducer works great and the pointer to `Extract.parse` was exactly correct.

I think this is ultimately a GHC bug - I inlined the relevant bits of doctest and it really does look like it should work; GHC getting very confused about which package `DummyDefs` belongs to reinforces that suspicion - so I've [reported it to GHCHQ](https://gitlab.haskell.org/ghc/ghc/issues/18070).

On the necessity of typechecking: interesting! It was added quite deliberately in 6cbe3f50a0de7e1e2365d1c286b8453643c9c29f. [`Haddock.Interface`](https://github.com/haskell/haddock/blob/8c6532636e6bd572455dfcf0b0d6e05f7033d110/haddock-api/src/Haddock/Interface.hs), which roughly corresponds to doctest's `Extract.hs`, also typechecks, though that might well be for Haddock-specific reasons that doctest isn't subject to; I can't immediately think why doctest would need to. Even aside from working around the bug here, it'd be nice to speed up everyone's doctests if it really is redundant.

@sol, do you recall what the original motivation was for performing typechecking during extraction?

**Comment by sol** [comment]
I don't remember, no.  If everything works without it, then I assume it can be skipped (make sure to test with a module that uses TH).

**Comment by jchia** [comment]
clash-prelude-1.2.2 seems to have a similar problem with the ghc-typelits-knownnat plugin when I run `cabal test doctests` on it:
```
Running 1 test suites...
Test suite doctests: RUNNING...

/data/jchia/stage/clash-prelude-1.2.2/src/Clash/Class/Resize.hs:1:1: error:
    Bad interface file: /home/jchia/.cabal/store/ghc-8.10.1/ghc-typelits-knownnat-0.7.2-9702d0f62de878476f1a3b3b7fb12750a74394fed1424bed0b5cb68266bff3b9/lib/GHC/TypeLits/KnownNat.hi
        Something is amiss; requested module  ghc-typelits-knownnat-0.7.2:GHC.TypeLits.KnownNat differs from name found in the interface file filepath-1.4.2.1:GHC.TypeLits.KnownNat (if these names look the same, try again with -dppr-debug)
  |
1 | {-|
  | ^
-i
-i/data/jchia/stage/clash-prelude-1.2.2/dist-newstyle/build/x86_64-linux/ghc-8.10.1/clash-prelude-1.2.2/build/autogen
-i/data/jchia/stage/clash-prelude-1.2.2/dist-newstyle/build/x86_64-linux/ghc-8.10.1/clash-prelude-1.2.2/build
-i/data/jchia/stage/clash-prelude-1.2.2/src
-package-env=-
-hide-all-packages
-no-user-package-db
-package-db=/home/jchia/.cabal/store/ghc-8.10.1/package.db
-package-db=/data/jchia/stage/clash-prelude-1.2.2/dist-newstyle/packagedb/ghc-8.10.1
-package-db=/data/jchia/stage/clash-prelude-1.2.2/dist-newstyle/build/x86_64-linux/ghc-8.10.1/clash-prelude-1.2.2/package.conf.inplace
-optP-include
```

**Comment by LeventErkok** [comment]
Just wanted to chime in and say I'm observing seg-faults too. And I do not have any "typechecker plugins." (Although I do have a tiny bit of Template Haskell, I'm not sure if that's the real culprit.)

**Comment by leonschoorl** [comment]
Actual seg-faults are something different

**Comment by LeventErkok** [comment]
@leonschoorl Definitely seeing seg-faults on my side:

```
$ SBV_TEST_ENVIRONMENT=local cabal new-run SBVDocTest -- --fast --no-magic
Up to date
SBVDocTest: Test platform: TestEnvLocal
[1]    1714 segmentation fault  SBV_TEST_ENVIRONMENT=local cabal new-run SBVDocTest -- --fast --no-magic
```

I'll try to see if I can create a way to replicate this on a simpler example.

**Comment by quasicomputational** [comment]
This bug seems to be quite specific to plugins and has been fixed with the release of GHC 8.10.2, so I'm closing this issue.

Please do open a new bug for the segfaulting with a reproducer!
