### ISSUE TITLE
doctest-0.10.1 doesn't support GHC 8.0.x

### ISSUE THREAD

**Issue by peti** [sol/doctest#125]
The current version of doctest refuses to compile with GHC 8.0.x:

~~~
Setup: At least the following dependencies are missing:

ghc >=7.0 && <7.12
~~~~

**Comment by trofi** [comment]
The real incompatibility will come from http://git.haskell.org/ghc.git/commitdiff/1e041b7382b6aa329e4ad9625439f811e0f27232

```
[10 of 16] Compiling Extract          ( src/Extract.hs, dist/build/Extract.o )

src/Extract.hs:234:31: error:
    Not in scope: type constructor or class ‘HsWithBndrs’
```

**Comment by deepfire** [comment]
@sol, where would one start looking to fix this?

**Comment by sol** [comment]
@deepfire If you want to work on this I'll make sure that I free up some time to review the code and get it merged.  I think only code in `src/Extract.hs` needs to be adapted.

**Comment by deepfire** [comment]
Commit replacing `HsWithBndrs`: https://git.haskell.org/ghc.git/commit/1e041b7382b6aa329e4ad9625439f811e0f27232

The commit message doesn't mention `HsWithBndrs` specifically, but refers to `Note [HsType binders]` in source code: https://git.haskell.org/ghc.git/blobdiff/b432e2f39c095d8acbb0cfcc63bd08436c7a3e49..1e041b7382b6aa329e4ad9625439f811e0f27232:/compiler/hsSyn/HsTypes.hs

**Comment by sol** [comment]
On Hackage as `doctest-0.11.0`.

**Comment by peti** [comment]
Compiles fine in Nixpkgs. Thank you  very much!
