### ISSUE TITLE
Support GHC 9.2

### ISSUE THREAD

**Issue by andreasabel** [sol/doctest#305]
Migration code might be at: https://gitlab.haskell.org/ghc/head.hackage/-/blob/master/patches/doctest-0.18.1.patch by @RyanGlScott (btw, it would be great if you opened a PR with the migrating patch...)

UPDATE: Blocked by
- [ ] hsc2hs https://github.com/haskell/hsc2hs/issues/64
- [x] ghc-paths https://github.com/simonmar/ghc-paths/pull/26

Blocking:
- [ ] cabal-doctest (https://github.com/haskellari/cabal-doctest/issues/70)

**Comment by LeventErkok** [comment]
@andreasabel @RyanGlScott 

Now that 9.2.1 is officially out, it'd be really nice to have this release. Here's what I'm seeing when trying to compile with 9.2.1:

```
[ 1 of 15] Compiling GhcUtil

src/GhcUtil.hs:100:7: error: Not in scope: ‘hscTarget’
    |
100 |       hscTarget = HscNothing
    |       ^^^^^^^^^
```

**Comment by RyanGlScott** [comment]
Just to clarify, I'm not a `doctest` maintainer. I often find myself writing patches for `head.hackage`, but there's no guarantee that the code in a `head.hackage` patch will correspond to the code you'd actually want to put in a new release. Among other reasons:

* `head.hackage` only needs to support the latest GHC release, so sometimes `head.hackage` patches won't compile on all GHC versions.
* I'm far from an expert on the libraries that I'm patching (`doctest` included), so some of the patches I write may deviate from the code style that a library's maintainers would prefer.
