### PR TITLE
Fix build with GHC 9.6

### LINKED ISSUE #394: Build failure on GHC 9.6
Looks like an API change on 9.6

```
doctest> [ 1 of 16] Compiling GhcUtil          ( src/GhcUtil.hs, dist/build/GhcUtil.o, dist/build/GhcUtil.dyn_o )
doctest> src/GhcUtil.hs:73:19: error: [GHC-88464]
doctest>     Data constructor not in scope: NoBackend :: Backend
doctest>     Suggested fix: Perhaps use variable ‘noBackend’ (imported from GHC)
doctest>    |
doctest> 73 |       backend   = NoBackend
doctest>    |                   ^^^^^^^^^
doctest> [ 2 of 16] Compiling Language.Haskell.GhciWrapper ( ghci-wrapper/src/Language/Haskell/GhciWrapper.hs, dist/build/Language/Haskell/GhciWrapper.o, dist/build/Language/Haskell/GhciWrapper.dyn_o )
doctest> [ 3 of 16] Compiling Interpreter      ( src/Interpreter.hs, dist/build/Interpreter.o, dist/build/Interpreter.dyn_o )
doctest> [ 4 of 16] Compiling Location         ( src/Location.hs, dist/build/Location.o, dist/build/Location.dyn_o )
doctest> [ 5 of 16] Compiling PackageDBs       ( src/PackageDBs.hs, dist/build/PackageDBs.o, dist/build/PackageDBs.dyn_o )
doctest> [ 6 of 16] Compiling Paths_doctest    ( dist/build/autogen/Paths_doctest.hs, dist/build/Paths_doctest.o, dist/build/Paths_doctest.dyn_o )
doctest> [ 7 of 16] Compiling Info             ( src/Info.hs, dist/build/Info.o, dist/build/Info.dyn_o )
doctest> [ 8 of 16] Compiling Options          ( src/Options.hs, dist/build/Options.o, dist/build/Options.dyn_o )
doctest> [ 9 of 16] Compiling Util             ( src/Util.hs, dist/build/Util.o, dist/build/Util.dyn_o )
error: builder for '/nix/store/7mn69kvw5wn7f1nr43qmal2f8n1akys4-doctest-0.20.1.drv' failed with exit code 1;
```

https://gitlab.homotopic.tech/horizon/horizon-core/-/jobs/161052

### PR DESCRIPTION
**Pull request by guibou**
Should close #394.

### CODE REVIEW

**Comment by sol** [comment]
@guibou hey, thanks for helping with this!

Can you please:
- Update `.github/workflows/build.yml`
- Make sure that CI passes

**Review by kazu-yamamoto — APPROVED** [review]
LGTM

**Comment by kazu-yamamoto** [comment]
@sol This PR lets doctest be buildable. Please merge this. You also need to modify the cabal files like `ghc >=8.0 && <9.7`.

One test fails. I will register a new issue.

**Comment by sol** [comment]
@kazu-yamamoto the build needs to pass before this can be merged.

**Comment by sol** [comment]
I include this commit in #401.
