### ISSUE TITLE
0.20.0 doesn't build on ghc 9.4.2

### ISSUE THREAD

**Issue by danwdart** [sol/doctest#383]
Removing version constraints to upgrade gave me:

```
src/Extract.hs:185:27: error:
    • Couldn't match expected type: Maybe a0 -> IO HscEnv
                  with actual type: IO HscEnv
    • The function ‘initializePlugins’
      is applied to two value arguments,
        but its type ‘HscEnv -> IO HscEnv’ has only one
      In the first argument of ‘liftIO’, namely
        ‘(initializePlugins hsc_env Nothing)’
      In a stmt of a 'do' block:
        hsc_env' <- liftIO (initializePlugins hsc_env Nothing)
    |
185 |       hsc_env' <- liftIO (initializePlugins hsc_env Nothing)
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Extract.hs:230:56: error:
    Variable not in scope: unpackHDS :: HsDoc GhcPs -> String
    Suggested fix: Perhaps use ‘unpackHDSC’ (imported from GHC)
    |
230 | docStringsFromModule mod = map (fmap (toLocated . fmap unpackHDS)) docs
    |                                                        ^^^^^^^^^

src/Extract.hs:235:26: error:
    • Couldn't match type: GenLocated SrcSpan (HsDoc GhcPs)
                     with: WithHsDocIdentifiers HsDocString GhcPs
      Expected: [(Maybe String, LHsDoc GhcPs)]
        Actual: [(Maybe String, GenLocated SrcSpan (LHsDoc GhcPs))]
    • In the first argument of ‘(++)’, namely ‘exports’
      In the second argument of ‘(++)’, namely ‘exports ++ decls’
      In the expression: header ++ exports ++ decls
    |
235 |     docs     = header ++ exports ++ decls
    |                          ^^^^^^^

src/Extract.hs:235:37: error:
    • Couldn't match type ‘HsDocString’
                     with ‘WithHsDocIdentifiers HsDocString GhcPs’
      Expected: [(Maybe String, LHsDoc GhcPs)]
        Actual: [(Maybe String, LHsDocString)]
    • In the second argument of ‘(++)’, namely ‘decls’
      In the second argument of ‘(++)’, namely ‘exports ++ decls’
      In the expression: header ++ exports ++ decls
    |
235 |     docs     = header ++ exports ++ decls
    |                                     ^^^^^

src/Extract.hs:322:31: error:
    • Expecting one more argument to ‘DocDecl’
      Expected a type, but ‘DocDecl’ has kind ‘* -> *’
    • In the type signature:
        fromDocDecl :: SrcSpan -> DocDecl -> (Maybe String, LHsDocString)
      In an equation for ‘extractDocStrings’:
          extractDocStrings
            = everythingBut
                (++)
                (([], False) `mkQ` fromLHsDecl `extQ` fromLDocDecl
                   `extQ` fromLHsDocString)
            where
                fromLHsDecl :: Selector (LHsDecl GhcPs)
                fromLHsDecl (L loc decl)
                  = case decl of
                      DocD _ x -> select (fromDocDecl (locA loc) x)
                      _ -> ...
                fromLDocDecl :: Selector (LDocDecl GhcPs)
                fromLDocDecl (L loc x) = select (fromDocDecl (locA loc) x)
                ....
    |
322 |     fromDocDecl :: SrcSpan -> DocDecl -> (Maybe String, LHsDocString)
```

Any idea about that one? Thanks!

**Comment by danwdart** [comment]
Looks like maybe a shim or a bit of CPP is required to switch between the new behaviour of some of these:

Strangely the first one wouldn't work on ghc 9.2 either:
https://hackage.haskell.org/package/ghc-9.0.2/docs/GHC-Runtime-Loader.html#v:initializePlugins
vs
https://hackage.haskell.org/package/ghc-9.2.4/docs/GHC-Runtime-Loader.html#v:initializePlugins
vs
https://hackage.haskell.org/package/ghc-9.4.2/docs/GHC-Runtime-Loader.html#v:initializePlugins

HDS now come in chunks:
https://hackage.haskell.org/package/ghc-9.2.4/docs/GHC-Hs-DocString.html#v:unpackHDS
vs
https://hackage.haskell.org/package/ghc-9.4.2/docs/GHC-Hs-DocString.html#v:unpackHDSC

I also see that there are several PRs in progress:

https://github.com/sol/doctest/pull/382
https://github.com/sol/doctest/pull/379
https://github.com/sol/doctest/pull/376
https://github.com/sol/doctest/pull/375

so I'll be doing my testing on one of those, so awesome job, folks.

**Comment by sol** [comment]
#382 by @eddiejessup looks promising, but there's a possible space leak that needs investigation.

**Comment by eddiejessup** [comment]
Just a shout that #382 is now merged, so if the problems are now gone maybe we can close this issue?

**Comment by danwdart** [comment]
Thanks - I see 0.20.1 in Hackage, I'll put it through my pipeline tonight and make sure I can build it with no issues.

**Comment by ysangkok** [comment]
@danwdart Did it work? Builds fine for me.

**Comment by danwdart** [comment]
Seems great to me. Nix may have forgotten to remove the check though... I'm just letting them know.
