### ISSUE TITLE
mkName issue with properties in doctest 0.9.11 with ghc-7.8.2

### ISSUE THREAD

**Issue by domdere** [sol/doctest#83]
Hi,

I'm using doctest-0.9.11 with ghc-7.8.2,

All my props fail with the following error:

```
<interactive>:1313:19:
    Not in scope: mkName
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))

<interactive>:1313:19:
    GHC stage restriction:
      mkName is used in a top-level splice or annotation,
      and must be imported, not defined locally
    In the first argument of polyQuickCheck, namely
      (mkName "doctest_prop")
    In the expression: polyQuickCheck (mkName "doctest_prop")
    In the splice: $(polyQuickCheck (mkName "doctest_prop"))
```

The only other versions for which `doctest` would build with ghc-7.8.2 are **0.9.10.2** and **0.9.10.2** 

with both **0.9.10.1** and **0.9.10.2** all my props fail with the error:

```
<interactive>:1306:14: lexical error at character '\8216'
```

I don't really understand why its complaining, as `mkName` is imported.
