### PR TITLE
Support GHC-9.2 (fix #305) (pr #306)

### LINKED ISSUE #305: Support GHC 9.2
Migration code might be at: https://gitlab.haskell.org/ghc/head.hackage/-/blob/master/patches/doctest-0.18.1.patch by @RyanGlScott (btw, it would be great if you opened a PR with the migrating patch...)

UPDATE: Blocked by
- [ ] hsc2hs https://github.com/haskell/hsc2hs/issues/64
- [x] ghc-paths https://github.com/simonmar/ghc-paths/pull/26

Blocking:
- [ ] cabal-doctest (https://github.com/haskellari/cabal-doctest/issues/70)

### PR DESCRIPTION
**Pull request by andreasabel**
GHC-9.2 compatibility (fix #305)

With this commit, based on @RyanGlScott's patch, building with
```
cabal v1-install --enable-tests --allow-newer=hsc2hs:base --allow-newer=ghc-paths:Cabal
cabal v1-test
```
the tests pass except for the `TemplateHaskell` ones (see below).
This could be due to some commented out code in `src/Extract.hs`,
cutting out the type-checking phase:
```diff
-  mods' <- if needsTemplateHaskellOrQQ mods then enableCompilation mods else return mods
+  --mods' <- if needsTemplateHaskellOrQQ mods then enableCompilation mods else return mods

-  let sortedMods = flattenSCCs (topSortModuleGraph False mods' Nothing)
-  reverse <$> mapM (loadModPlugins >=> parseModule >=> typecheckModule >=> loadModule) sortedMods
+  let sortedMods = flattenSCCs
+#if __GLASGOW_HASKELL__ >= 901
+                     $ filterToposortToModules
+#endif
+                     $ topSortModuleGraph False mods Nothing
+  reverse <$> mapM (loadModPlugins >=> parseModule) sortedMods
```
@RyanGlScott, do you remember why you did this change?

Test failure:
```
test/extract/th/Foo.hs:8:7: warning: [-Woperator-whitespace-ext-conflict]
    The prefix use of a ‘$’ would denote an untyped splice
      were the TemplateHaskell extension enabled.
    Suggested fix: add whitespace after the ‘$’.
  |
8 | foo = $(bar)
  |       ^

test/extract/th/Foo.hs:8:7: error:
    parse error on input ‘$’
    Perhaps you intended to use TemplateHaskell
  |
8 | foo = $(bar)
  |       ^

Failures:

  test/ExtractSpec.hs:91:5:
  1) Extract, extract (regression tests), works with a module that splices in an expression from an other module
       uncaught exception: ExitCode
       ExitFailure 1

  To rerun use: --match "/Extract/extract (regression tests)/works with a module that splices in an expression from an other module/"

Randomized with seed 107198347
```

### CODE REVIEW

**Comment by RyanGlScott** [comment]
> do you remember why you did this change?

This came about as a result of https://gitlab.haskell.org/ghc/head.hackage/-/issues/30, where we were trying to figure out how to make `pandoc` compile with HEAD (rather than 9.2). @mpickering suggested the Template Haskell change. @mpickering, do you recall why this was necessary?

**Comment by mpickering** [comment]
I will try and reproduce.

**Comment by mpickering** [comment]
Here's a fixed version of the patch.

```
commit 49b76645a356931d299cabe52ae16845463863b1
Author: Matthew Pickering <matthewtpickering@gmail.com>
Date:   Thu Nov 4 12:39:33 2021 +0000

    fix 9.2 patch

diff --git a/src/Extract.hs b/src/Extract.hs
index 9f08e00..c58be45 100644
--- a/src/Extract.hs
+++ b/src/Extract.hs
@@ -67,7 +67,6 @@ import           GHC.Runtime.Loader (initializePlugins)
 #endif
 
 #if __GLASGOW_HASKELL__ >= 901
-import           GHC.Driver.Env
 import           GHC.Unit.Module.Graph
 #endif
 
@@ -207,13 +206,17 @@ parse args = withGhc args $ \modules_ -> withTempOutputDir $ do
 #if __GLASGOW_HASKELL__ >= 806
     -- Since GHC 8.6, plugins are initialized on a per module basis
     loadModPlugins modsum = do
+      setSessionDynFlags (GHC.ms_hspp_opts modsum)
       hsc_env <- getSession
+
 # if __GLASGOW_HASKELL__ >= 903
       hsc_env' <- liftIO (initializePlugins hsc_env Nothing)
-      return $ modsum { ms_hspp_opts = hsc_dflags hsc_env' }
+      setSession hsc_env'
+      return $ modsum
 # elif __GLASGOW_HASKELL__ >= 901
       hsc_env' <- liftIO (initializePlugins hsc_env)
-      return $ modsum { ms_hspp_opts = hsc_dflags hsc_env' }
+      setSession hsc_env'
+      return $ modsum
 # else
       dynflags' <- liftIO (initializePlugins hsc_env (GHC.ms_hspp_opts modsum))
       return $ modsum { ms_hspp_opts = dynflags' }
diff --git a/src/GhcUtil.hs b/src/GhcUtil.hs
index 274c9ca..de36558 100644
--- a/src/GhcUtil.hs
+++ b/src/GhcUtil.hs
@@ -81,7 +81,8 @@ handleStaticFlags flags = return $ map noLoc $ flags
 handleDynamicFlags :: GhcMonad m => [Located String] -> m [String]
 handleDynamicFlags flags = do
 #if __GLASGOW_HASKELL__ >= 901
-  parseDynamicFlags' <- parseDynamicFlags =<< getLogger
+  logger <- getLogger
+  let parseDynamicFlags' = parseDynamicFlags logger
 #else
   let parseDynamicFlags' = parseDynamicFlags
 #endif
```

**Comment by andreasabel** [comment]
Thanks @mpickering !  Works for me!  (I had to remember `git apply`...)

Q: Why is the patch to `GhcUtil` necessary?  What difference does this change make?:
```diff
-  parseDynamicFlags' <- parseDynamicFlags =<< getLogger
+  logger <- getLogger
+  let parseDynamicFlags' = parseDynamicFlags logger
```

**Comment by mpickering** [comment]
> Thanks @mpickering ! Works for me! (I had to remember `git apply`...)
> 
> Q: Why is the patch to `GhcUtil` necessary? What difference does this change make?:
> 
> ```diff
> -  parseDynamicFlags' <- parseDynamicFlags =<< getLogger
> +  logger <- getLogger
> +  let parseDynamicFlags' = parseDynamicFlags logger
> ```

This makes the patch compile for me.. it didn't before.
