### ISSUE TITLE
GHC API changes break build on 8.4.1

### ISSUE THREAD

**Issue by deepfire** [sol/doctest#177]
Build failure on GHC 8.4.1-alpha1:
```
Building library for doctest-0.10.1..
[ 1 of 16] Compiling GhcUtil          ( src/GhcUtil.hs, dist/build/GhcUtil.o )

src/GhcUtil.hs:24:1: error:
    Could not find module ‘StaticFlags’
    Use -v to see a list of the files searched for.
   |
24 | import           StaticFlags (discardStaticFlags)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The module was dropped in: https://github.com/ghc/ghc/commit/bbd3c399939311ec3e308721ab87ca6b9443f358

**Comment by deepfire** [comment]
Also:
```
[10 of 16] Compiling Extract          ( src/Extract.hs, dist/build/Extract.o )

src/Extract.hs:87:15: error:
    • Variable not in scope:
        needsTemplateHaskell :: ModuleGraph -> Bool
    • Perhaps you meant ‘needsTemplateHaskellOrQQ’ (imported from GHC)
   |
87 |   mods' <- if needsTemplateHaskell mods then enableCompilation mods else return mods
   |               ^^^^^^^^^^^^^^^^^^^^

src/Extract.hs:104:31: error:
    • Couldn't match expected type ‘[ModSummary]’
                  with actual type ‘ModuleGraph’
    • In the second argument of ‘map’, namely ‘modGraph’
      In the expression: map upd modGraph
      In an equation for ‘modGraph'’: modGraph' = map upd modGraph
    |
104 |       let modGraph' = map upd modGraph
    |                               ^^^^^^^^

src/Extract.hs:105:7: error:
    • Couldn't match type ‘[ModSummary]’ with ‘ModuleGraph’
      Expected type: Ghc ModuleGraph
        Actual type: Ghc [ModSummary]
    • In a stmt of a 'do' block: return modGraph'
      In the expression:
        do let enableComp d = ...
           modifySessionDynFlags enableComp
           let upd m = ...
           let modGraph' = map upd modGraph
           ....
      In an equation for ‘enableCompilation’:
          enableCompilation modGraph
            = do let enableComp d = ...
                 modifySessionDynFlags enableComp
                 let upd m = ...
                 ....
    |
105 |       return modGraph'
    |       ^^^^^^^^^^^^^^^^
```

**Comment by quasicomputational** [comment]
FWIW, @RyanGlScott wrote [a patch for head.hackage](https://github.com/hvr/head.hackage/blob/master/patches/doctest-0.13.0.patch), which might be a useful jumping-off point (or even getting us all the way there?). I can't speak for him as to whether it's 100% baked, but you can see, e.g., in [this lens Travis build on 8.4 with head.hackage](https://travis-ci.org/ekmett/lens/jobs/330618198) that the doctests work.

**Comment by sol** [comment]
Fixed in `0.14.0`.
